### ISSUE TITLE
apk command in the container is always killed..

### ISSUE THREAD

**Issue by HaoyunJi** [nicolaka/netshoot#160]
netshoot-bfd76dbb7-4p5ck:~# cd /efs
sed -i 's/http:/https:/g' /etc/apk/repositories
apk add rsync
**Killed**
netshoot-bfd76dbb7-4p5ck:/efs# apk add rsync
Killed

**Comment by peter-tar** [comment]
Hi @HaoyunJi,
Could you share what was the root cause or how you solved it? I'm experiencing the same problem. 

I have a suspicion that it isn't directly related to the netshoot image specifically. When I am running it standalone it works just fine, I only get the kills when I'm using it as a k8s debug container. At first glance these kills seem to be related to memory, but there is plenty of resources on the node and the container I am running it next to has a very high limit. No namespace limits either. 
Thanks!

**Comment by peter-tar** [comment]
I figured it out. Just in case someone finds this issue in the future, here's what the problem was.
It was the memory limit, unsurprisingly. I did set the it very high, but there was a VPA resource that overrode it with a much smaller value that I missed. 
Launching the debug container with the `--profile=sysadmin` flag also helped me troubleshoot it as it allowed me to read the output of dmesg and confirm that it was indeed the OOMKiller that killed my processes.
